src/Entity/Parts/Footprint.php
<?php
/**
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 * Copyright (C) 2019 - 2022 Jan Böhmer (https://github.com/jbtronics)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace App\Entity\Parts;

use Doctrine\Common\Collections\Criteria;
use ApiPlatform\Doctrine\Common\Filter\DateFilterInterface;
use ApiPlatform\Doctrine\Orm\Filter\DateFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Link;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\OpenApi\Model\Operation;
use ApiPlatform\Serializer\Filter\PropertyFilter;
use App\ApiPlatform\Filter\LikeFilter;
use App\Entity\Attachments\Attachment;
use App\Entity\EDA\EDAFootprintInfo;
use App\Repository\Parts\FootprintRepository;
use App\Entity\Base\AbstractStructuralDBElement;
use Doctrine\Common\Collections\ArrayCollection;
use App\Entity\Attachments\FootprintAttachment;
use App\Entity\Base\AbstractPartsContainingDBElement;
use App\Entity\Parameters\FootprintParameter;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This entity represents a footprint of a part (its physical dimensions and shape).
 *
 * @extends AbstractPartsContainingDBElement<FootprintAttachment, FootprintParameter>
 */
#[ORM\Entity(repositoryClass: FootprintRepository::class)]
#[ORM\Table('`footprints`')]
#[ORM\Index(columns: ['name'], name: 'footprint_idx_name')]
#[ORM\Index(columns: ['parent_id', 'name'], name: 'footprint_idx_parent_name')]
#[ApiResource(
    operations: [
        new Get(security: 'is_granted("read", object)'),
        new GetCollection(security: 'is_granted("@footprints.read")'),
        new Post(securityPostDenormalize: 'is_granted("create", object)'),
        new Patch(security: 'is_granted("edit", object)'),
        new Delete(security: 'is_granted("delete", object)'),
    ],
    normalizationContext: ['groups' => ['footprint:read', 'api:basic:read'], 'openapi_definition_name' => 'Read'],
    denormalizationContext: ['groups' => ['footprint:write', 'api:basic:write', 'attachment:write', 'parameter:write'], 'openapi_definition_name' => 'Write'],
)]
#[ApiResource(
    uriTemplate: '/footprints/{id}/children.{_format}',
    operations: [
        new GetCollection(
            openapi: new Operation(summary: 'Retrieves the children elements of a footprint.'),
            security: 'is_granted("@footprints.read")'
        )
    ],
    uriVariables: [
        'id' => new Link(fromProperty: 'children', fromClass: Footprint::class)
    ],
    normalizationContext: ['groups' => ['footprint:read', 'api:basic:read'], 'openapi_definition_name' => 'Read']
)]
#[ApiFilter(PropertyFilter::class)]
#[ApiFilter(LikeFilter::class, properties: ["name", "comment"])]
#[ApiFilter(DateFilter::class, strategy: DateFilterInterface::EXCLUDE_NULL)]
#[ApiFilter(OrderFilter::class, properties: ['name', 'id', 'addedDate', 'lastModified'])]
class Footprint extends AbstractPartsContainingDBElement
{
    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'children')]
    #[ORM\JoinColumn(name: 'parent_id')]
    #[Groups(['footprint:read', 'footprint:write'])]
    #[ApiProperty(readableLink: false, writableLink: false)]
    protected ?AbstractStructuralDBElement $parent = null;

    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: self::class)]
    #[ORM\OrderBy(['name' => Criteria::ASC])]
    protected Collection $children;

    #[Groups(['footprint:read', 'footprint:write'])]
    protected string $comment = '';

    /**
     * @var Collection<int, FootprintAttachment>
     */
    #[Assert\Valid]
    #[ORM\OneToMany(mappedBy: 'element', targetEntity: FootprintAttachment::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['name' => Criteria::ASC])]
    #[Groups(['footprint:read', 'footprint:write'])]
    protected Collection $attachments;

    #[ORM\ManyToOne(targetEntity: FootprintAttachment::class)]
    #[ORM\JoinColumn(name: 'id_preview_attachment', onDelete: 'SET NULL')]
    #[Groups(['footprint:read', 'footprint:write'])]
    protected ?Attachment $master_picture_attachment = null;

    /**
     * @var FootprintAttachment|null
     */
    #[ORM\ManyToOne(targetEntity: FootprintAttachment::class)]
    #[ORM\JoinColumn(name: 'id_footprint_3d')]
    #[Groups(['footprint:read', 'footprint:write'])]
    protected ?FootprintAttachment $footprint_3d = null;

    /** @var Collection<int, FootprintParameter>
     */
    #[Assert\Valid]
    #[ORM\OneToMany(mappedBy: 'element', targetEntity: FootprintParameter::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['group' => Criteria::ASC, 'name' => 'ASC'])]
    #[Groups(['footprint:read', 'footprint:write'])]
    protected Collection $parameters;

    #[Groups(['footprint:read'])]
    protected ?\DateTimeImmutable $addedDate = null;
    #[Groups(['footprint:read'])]
    protected ?\DateTimeImmutable $lastModified = null;

    #[Assert\Valid]
    #[ORM\Embedded(class: EDAFootprintInfo::class)]
    #[Groups(['full', 'footprint:read', 'footprint:write'])]
    protected EDAFootprintInfo $eda_info;

    public function __construct()
    {
        parent::__construct();
        $this->children = new ArrayCollection();
        $this->attachments = new ArrayCollection();
        $this->parameters = new ArrayCollection();
        $this->eda_info = new EDAFootprintInfo();
    }

    /****************************************
     * Getters
     ****************************************/

    /**
     * Returns the 3D Model associated with this footprint.
     */
    public function getFootprint3d(): ?FootprintAttachment
    {
        return $this->footprint_3d;
    }

    /********************************************************************************
     *
     *   Setters
     *
     *********************************************************************************/
    /**
     * Sets the 3D Model associated with this footprint.
     *
     * @param FootprintAttachment|null $new_attachment The new 3D Model
     */
    public function setFootprint3d(?FootprintAttachment $new_attachment): self
    {
        $this->footprint_3d = $new_attachment;

        return $this;
    }

    public function getEdaInfo(): EDAFootprintInfo
    {
        return $this->eda_info;
    }

    public function setEdaInfo(EDAFootprintInfo $eda_info): Footprint
    {
        $this->eda_info = $eda_info;
        return $this;
    }
}

src/Entity/Parts/InfoProviderReference.php
<?php
/*
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 *  Copyright (C) 2019 - 2023 Jan Böhmer (https://github.com/jbtronics)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);


namespace App\Entity\Parts;

use App\Services\InfoProviderSystem\DTOs\SearchResultDTO;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Embeddable;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * This class represents a reference to a info provider inside a part.
 * @see \App\Tests\Entity\Parts\InfoProviderReferenceTest
 */
#[Embeddable]
class InfoProviderReference
{

    /** @var string|null The key referencing the provider used to get this part, or null if it was not provided by a data provider */
    #[Column(type: Types::STRING, nullable: true)]
    #[Groups(['provider_reference:read', 'full'])]
    private ?string $provider_key = null;

    /** @var string|null The id of this part inside the provider system or null if the part was not provided by a data provider */
    #[Column(type: Types::STRING, nullable: true)]
    #[Groups(['provider_reference:read', 'full'])]
    private ?string $provider_id = null;

    /**
     * @var string|null The url of this part inside the provider system or null if this info is not existing
     */
    #[Column(type: Types::STRING, nullable: true)]
    #[Groups(['provider_reference:read', 'full'])]
    private ?string $provider_url = null;

    #[Column(type: Types::DATETIME_IMMUTABLE, nullable: true,  options: ['default' => null])]
    #[Groups(['provider_reference:read', 'full'])]
    private ?\DateTimeImmutable $last_updated = null;

    /**
     * Constructing is forbidden from outside.
     */
    private function __construct()
    {

    }

    /**
     * Returns the key usable to identify the provider, which provided this part. Returns null, if the part was not created by a provider.
     * @return string|null
     */
    public function getProviderKey(): ?string
    {
        return $this->provider_key;
    }

    /**
     * Returns the id of this part inside the provider system or null if the part was not provided by a data provider.
     * @return string|null
     */
    public function getProviderId(): ?string
    {
        return $this->provider_id;
    }

    /**
     * Returns the url of this part inside the provider system or null if this info is not existing.
     * @return string|null
     */
    public function getProviderUrl(): ?string
    {
        return $this->provider_url;
    }

    /**
     * Gets the time, when the part was last time updated by the provider.
     */
    public function getLastUpdated(): ?\DateTimeImmutable
    {
        return $this->last_updated;
    }

    /**
     * Returns true, if this part was created based on infos from a provider.
     * Or false, if this part was created by a user manually.
     * @return bool
     */
    public function isProviderCreated(): bool
    {
        return $this->provider_key !== null;
    }

    /**
     * Creates a new instance, without any provider information.
     * Use this for parts, which are created by a user manually.
     * @return InfoProviderReference
     */
    public static function noProvider(): self
    {
        $ref = new InfoProviderReference();
        $ref->provider_key = null;
        $ref->provider_id = null;
        $ref->provider_url = null;
        $ref->last_updated = null;
        return $ref;
    }

    /**
     * Creates a reference to an info provider based on the given parameters.
     * @param  string  $provider_key
     * @param  string  $provider_id
     * @param  string|null  $provider_url
     * @return self
     */
    public static function providerReference(string $provider_key, string $provider_id, ?string $provider_url = null): self
    {
        $ref = new InfoProviderReference();
        $ref->provider_key = $provider_key;
        $ref->provider_id = $provider_id;
        $ref->provider_url = $provider_url;
        $ref->last_updated = new \DateTimeImmutable();
        return $ref;
    }

    /**
     * Creates a reference to an info provider based on the given Part DTO
     * @param  SearchResultDTO  $dto
     * @return self
     */
    public static function fromPartDTO(SearchResultDTO $dto): self
    {
        $ref = new InfoProviderReference();
        $ref->provider_key = $dto->provider_key;
        $ref->provider_id = $dto->provider_id;
        $ref->provider_url = $dto->provider_url;
        $ref->last_updated = new \DateTimeImmutable();
        return $ref;
    }
}

src/Entity/Parts/PartTraits/AssociationTrait.php
<?php
/*
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 *  Copyright (C) 2019 - 2023 Jan Böhmer (https://github.com/jbtronics)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);


namespace App\Entity\Parts\PartTraits;

use App\Entity\Parts\PartAssociation;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints\Valid;
use Doctrine\ORM\Mapping as ORM;

trait AssociationTrait
{
    /**
     * @var Collection<PartAssociation> All associations where this part is the owner
     */
    #[Valid]
    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: PartAssociation::class,
        cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[Groups(['part:read', 'part:write', 'full'])]
    protected Collection $associated_parts_as_owner;

    /**
     * @var Collection<PartAssociation> All associations where this part is the owned/other part
     */
    #[Valid]
    #[ORM\OneToMany(mappedBy: 'other', targetEntity: PartAssociation::class,
        cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[Groups(['part:read'])]
    protected Collection $associated_parts_as_other;

    /**
     * Returns all associations where this part is the owner.
     * @return Collection<PartAssociation>
     */
    public function getAssociatedPartsAsOwner(): Collection
    {
        return $this->associated_parts_as_owner;
    }

    /**
     * Add a new association where this part is the owner.
     * @param  PartAssociation  $association
     * @return $this
     */
    public function addAssociatedPartsAsOwner(PartAssociation $association): self
    {
        //Ensure that the association is really owned by this part
        $association->setOwner($this);

        $this->associated_parts_as_owner->add($association);
        return $this;
    }

    /**
     * Remove an association where this part is the owner.
     * @param  PartAssociation  $association
     * @return $this
     */
    public function removeAssociatedPartsAsOwner(PartAssociation $association): self
    {
        $this->associated_parts_as_owner->removeElement($association);
        return $this;
    }

    /**
     * Returns all associations where this part is the owned/other part.
     * If you want to modify the association, do it on the owning part
     * @return Collection<PartAssociation>
     */
    public function getAssociatedPartsAsOther(): Collection
    {
        return $this->associated_parts_as_other;
    }

    /**
     * Returns all associations where this part is the owned or other part.
     * @return Collection<PartAssociation>
     */
    public function getAssociatedPartsAll(): Collection
    {
        return new ArrayCollection(
            array_merge(
                $this->associated_parts_as_owner->toArray(),
                $this->associated_parts_as_other->toArray()
            )
        );
    }
}

templates/parts/info/_associations.html.twig
{% import "helper.twig" as helper %}

{% macro assoc_row(assoc) %}
    {# @var assoc \App\Entity\Parts\PartAssociation #}
    <tr>
        <td>{{ helper.part_icon_link(assoc.owner) }}</td>
        <td>{{ assoc.typeTranslationKey | trans }}</td>
        <td>{{ helper.part_icon_link(assoc.other) }}</td>
        <td>{{ assoc.comment }}</td>
    </tr>
{% endmacro %}

{% macro assoc_table(assocs, caption) %}
    <div class="table-responsive">
        <table class="table table-striped table-hover caption-top">
            <caption>{{ caption | trans }}:</caption>
            <thead>
                <tr>
                    <th>{% trans %}part_association.table.from{% endtrans %}</th>
                    <th>{% trans %}part_association.table.type{% endtrans %}</th>
                    <th>{% trans %}part_association.table.to{% endtrans %}</th>
                    <th>{% trans %}part_association.edit.comment{% endtrans %}</th>
                </tr>
            </thead>
            <tbody>
            {% for assoc in assocs %}
                {{ _self.assoc_row(assoc) }}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endmacro %}

{% if part.associatedPartsAsOwner is not empty %}
    {{ _self.assoc_table(part.associatedPartsAsOwner, 'part_association.table.from_this_part') }}
{% endif %}

{% if part.associatedPartsAsOther is not empty %}
    {{ _self.assoc_table(part.associatedPartsAsOther, 'part_association.table.to_this_part') }}
{% endif %}

templates/parts/info/_extended_infos.html.twig
{% import "helper.twig" as helper %}

<table class="table table-striped table-hover table-sm w-100 table-responsive-sm">
    <tbody>
    <tr> {# Creation date #}
        <td>{% trans %}createdAt{% endtrans %}</td>
        <td>{{ part.addedDate | format_datetime("long")}}</td>
    </tr>

    <tr>
        <td>{% trans %}user.creating_user{% endtrans %}</td>
        <td>{% if is_granted('show_history', part) %}
                {{ creating_user(part).fullName(true) ?? 'Unknown'|trans }}
            {% else %}
                {% trans %}accessDenied{% endtrans %}
            {% endif %}
        </td>
    </tr>

    <tr> {# Last modified date #}
        <td>{% trans %}lastModified{% endtrans %}</td>
        <td>{{ part.lastModified | format_datetime("long")}}</td>
    </tr>

    <tr>
        <td>{% trans %}user.last_editing_user{% endtrans %}</td>
        <td>{% if is_granted('show_history', part) %}
                {{ last_editing_user(part).fullName(true) ?? 'Unknown'|trans }}
            {% else %}
                {% trans %}accessDenied{% endtrans %}
            {% endif %}
        </td>
    </tr>

    <tr> {# ID #}
        <td>{% trans %}id.label{% endtrans %}</td>
        <td>{{ part.iD }}</td>
    </tr>

    <tr> {# IPN #}
        <td>{% trans %}part.edit.ipn{% endtrans %}</td>
        <td>{{ part.ipn ?? 'part.ipn.not_defined'|trans }}</td>
    </tr>

    <tr> {# Favorite status #}
        <td>{% trans %}part.isFavorite{% endtrans %}</td>
        <td>{{ helper.boolean_badge(part.favorite) }}</td>
    </tr>

    <tr> {# Build status #}
        <td>{% trans %}part.is_build_part{% endtrans %}</td>
        <td>{{ helper.boolean_badge(part.projectBuildPart) }}
            {% if part.projectBuildPart %}(<a href="{{ entity_url(part.builtProject, "edit") }}">{{ part.builtProject.name }}</a>){% endif %}</td>
    </tr>

    <tr>
        <td>{% trans %}part.minOrderAmount{% endtrans %}</td>
        <td>{% if  pricedetail_helper.minOrderAmount(part) %}
                {{ pricedetail_helper.minOrderAmount(part) | format_amount(part.partUnit) }}
            {% else %}
                {% trans %}Unknown{% endtrans %}
            {% endif %}
        </td>
    </tr>

    <tr>
        <td>{% trans %}part.info_provider_reference{% endtrans %}</td>
        <td>
            {% if part.providerReference.providerCreated %}
                {% if part.providerReference.providerUrl %}
                    <a href="{{ part.providerReference.providerUrl }}" rel="noopener">
                {% endif %}
                <span title="{{ part.providerReference.providerKey }}">{{ info_provider_label(part.providerReference.providerKey)|default(part.providerReference.providerKey) }}</span>: {{ part.providerReference.providerId }}
                <span> ({{ part.providerReference.lastUpdated | format_datetime() }})</span>
                {% if part.providerReference.providerUrl %}
                    </a>
                {% endif %}

                {# Show last updated date #}

            {% else %}
                {{ helper.boolean_badge(part.providerReference.providerCreated) }}
            {% endif %}

        </td>
    </tr>

    <tr>
        <td>{% trans %}part.edit.tab.eda{% endtrans %}</td>
        <td>
            <b>{% trans %}eda_info.reference_prefix{% endtrans %}:</b> {{ part.edaInfo.referencePrefix ?? part.category.edaInfo.referencePrefix ?? "" }}
            <br>
            <b>{% trans %}eda_info.value{% endtrans %}:</b> {{ part.edaInfo.value }}
            <br>
            <b>{% trans %}eda_info.visibility{% endtrans %}:</b> {{ helper.boolean_badge( part.edaInfo.visibility ?? part.category.edaInfo.visibility) }}
            <br>
            <b>{% trans %}eda_info.exclude_from_bom{% endtrans %}:</b> {{ helper.boolean_badge( part.edaInfo.excludeFromBom ?? part.category.edaInfo.excludeFromBom ?? false) }}
            <br>
            <b>{% trans %}eda_info.exclude_from_board{% endtrans %}:</b> {{ helper.boolean_badge( part.edaInfo.excludeFromBoard ?? part.category.edaInfo.excludeFromBoard ?? false) }}
            <br>
            <b>{% trans %}eda_info.exclude_from_sim{% endtrans %}:</b> {{ helper.boolean_badge( part.edaInfo.excludeFromSim ?? part.category.edaInfo.excludeFromSim ?? false) }}
            <br>
            <b>{% trans %}eda_info.kicad_symbol{% endtrans %}:</b> {{ part.edaInfo.kicadSymbol ?? part.category.edaInfo.kicadSymbol ?? "" }}
            <br>
            <b>{% trans %}eda_info.kicad_footprint{% endtrans %}:</b> {{ part.edaInfo.kicadFootprint ?? part.footprint.edaInfo.kicadFootprint ?? "" }}
        </td>
    </tr>
    </tbody>
</table>

templates/parts/info/_history.html.twig
<div class="mt-2">
    {% if datatable is not null %}
        {% import "components/history_log_macros.html.twig" as log %}
        {{ log.element_history_component(datatable) }}
    {% endif %}
</div>

templates/parts/info/_projects.html.twig
{% import "components/attachments.macro.html.twig" as attachments %}
{% import "helper.twig" as helper %}

<table class="table table-striped table-sm table-hover table-responsive-sm">
    <thead>
    <tr>
        <th></th>
        <th>{% trans %}entity.info.name{% endtrans %}</th>
        <th>{% trans %}description.label{% endtrans %}</th>
        <th>{% trans %}project.bom.quantity{% endtrans %}</th>
        <th>{% trans %}project.bom.mountnames{% endtrans %}</th>
    </tr>
    </thead>

    <tbody>
    {% for bom_entry in part.projectBomEntries %}
        {# @var bom_entry App\Entity\Project\ProjectBOMEntry #}
    <tr>
        <td>{% if bom_entry.project.masterPictureAttachment is not null %}{{ attachments.attachment_icon(bom_entry.project.masterPictureAttachment, attachment_manager) }}{% endif %}</td>
        <td><a href="{{ path('project_info', {'id': bom_entry.project.iD}) }}">{{ bom_entry.project.name }}</a></td> {# Name #}
        <td>{{ bom_entry.project.description|format_markdown }}</td> {# Description #}
        <td>{{ bom_entry.quantity | format_amount(part.partUnit) }}</td>
        <td>{% for tag in bom_entry.mountnames|split(',') %}
                <span class="badge bg-secondary badge-secondary" >{{ tag | trim }}</span>
            {% endfor %}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<a class="btn btn-success" {% if not is_granted('@projects.edit') %}disabled{% endif %}
   href="{{ path('project_add_parts_no_id', {"parts": part.id, "_redirect":  uri_without_host(app.request)}) }}">
    <i class="fa-solid fa-magnifying-glass-plus fa-fw"></i>
    {% trans %}part.info.add_part_to_project{% endtrans %}
</a>

templates/parts/info/_sidebar.html.twig
{% import "helper.twig" as helper %}

{% if timeTravel is not null %}
    <b class="mb-2">{% trans with {'%timestamp%': timeTravel|format_datetime('short')} %}part.info.timetravel_hint{% endtrans %}</b>
{% endif %}

{% if part.projectBuildPart %}
    <b class="mb-2">{% trans %}part.info.projectBuildPart.hint{% endtrans %}:  <a href="{{ entity_url(part.builtProject) }}">{{ part.builtProject.name }}</a></b>
{% endif %}

<div class="mb-3">
<span class="text-muted" title="{% trans %}lastModified{% endtrans %}">
    <i class="fas fa-history fa-fw"></i>  {{ helper.entity_last_modified(part) }}
</span>
    <br>
    <span class="text-muted mt-1" title="{% trans %}createdAt{% endtrans %}">
    <i class="fas fa-calendar-plus fa-fw"></i> {{ helper.entity_created_at(part) }}
</span>
</div>

{# Part mass #}
{% if part.mass %}
    <div>
        <h6>
            <span class="badge bg-secondary" title="{% trans %}part.mass.tooltip{% endtrans %}"><i class="fas fa-weight-hanging fa-fw"></i> {{ part.mass | format_si("g") }}</span>
        </h6>
    </div>
{% endif %}

{# Needs Review tag #}
{% if part.needsReview %}
    <div class="mt-1">
        <h6>
            <span class="badge bg-warning"><i class="fas fa-ambulance fa-fw"></i> {% trans %}part.needs_review.badge{% endtrans %}</span>
        </h6>
    </div>
{% endif %}

{# Favorite Status tag #}
{% if part.favorite %}
    <div class="mt-1">
        <h6>
            <span class="badge bg-success"><i class="fas fa-award fa-fw"></i> {% trans %}part.favorite.badge{% endtrans %}</span>
        </h6>
    </div>
{% endif %}

{% if part.obsolete %}
    <div class="mt-1">
        <h6>
            <span class="badge bg-danger"><i class="fas fa-ghost fa-fw"></i> {% trans %}part.obsolete.badge{% endtrans %}</span>
        </h6>
    </div>
{% endif %}

{# Manufacturing status tag #}
<div class="mt-1">
    <h6>
        {{ helper.m_status_to_badge(part.manufacturingStatus) }}
    </h6>
</div>

{# Show tags #}
{% if part.tags is not empty %}
    <div class="mt-1">
        <h6 style="line-height: 1.5;">
            {{ helper.string_to_tags(part.tags) }}
        </h6>
    </div>
{% endif %}

{# Info provider badge #}
{% if part.providerReference.providerCreated %}
    <div class="mt-1">
        <h6>
            <a href="{{ part.providerReference.providerUrl ?? '#' }}" class="badge bg-info badge-info" title="{% trans %}part.info_provider_reference.badge{% endtrans %}">
                <i class="fa-solid fa-cloud"></i>
                {{ info_provider_label(part.providerReference.providerKey)|default(part.providerReference.providerKey) }}
            </a>
        </h6>
    </div>
{% endif %}

templates/parts/info/_specifications.html.twig
{# var \App\Entity\Parts\Part part #}
{% import "helper.twig" as helper %}

{% for name, parameters in part.groupedParameters %}
    {% if name is not empty %}<h5 class="mt-1">{{ name }}</h5>{% endif %}
    {{ helper.parameters_table(parameters) }}
{% endfor %}

{% if description_params is not empty %}
    <h5 class="mt-1">{% trans %}parameters.extracted_from_description{% endtrans %}</h5>
    {{ helper.parameters_table(description_params) }}
{% endif %}

{% if comment_params is not empty %}
    <h5 class="mt-1">{% trans %}parameters.auto_extracted_from_comment{% endtrans %}</h5>
    {{ helper.parameters_table(comment_params) }}
{% endif %}